# Generated by Django 3.0.5 on 2020-04-01 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mooviee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('rating', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooviee.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('movies', models.ManyToManyField(through='movie_list.MovieAssignment', to='mooviee.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooviee.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='movieassignment',
            name='movie_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_list.MovieList'),
        ),
        migrations.AddField(
            model_name='movieassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mooviee.Profile'),
        ),
    ]
